### ISSUE TITLE
5/5 watch => on_changes

### ISSUE THREAD

**Issue by Linuturk** [Linuturk/salt-sprint#100]
also a _in call that reverses like before

**Comment by Linuturk** [comment]
add note used to be watch in previous versions

**Comment by Linuturk** [comment]
don't remove watch. specify it adds additional behavor. new slides for on_changes

**Comment by Linuturk** [comment]
@gtmanfred want to tackle these new slides?

**Comment by gtmanfred** [comment]
Will try to get to this this week.
